#!/bin/bash

app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
source /usr/share/yunohost/helpers

path=$(ynh_app_setting_get $app path)
final_path=$(ynh_app_setting_get $app final_path)
domain=$(ynh_app_setting_get $app domain)
is_public=$(ynh_app_setting_get $app is_public)

# Backup sources & data
ynh_backup "$final_path" "sources"

# Copy Nginx and YunoHost parameters to make the script "standalone"
ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf" "nginx.conf"

ynh_backup "/etc/yunohost/apps/$app/" "yunohost"

# Backup systemd service
ynh_backup "/etc/systemd/system/$app.service" "systemd.service"
