#!/bin/bash

source .fonctions       # Charge les fonctions génériques habituellement utilisées dans le script

CLEAN_SETUP () {
# Nettoyage des résidus d'installation non pris en charge par le script remove.
# Pas de nettoyage supplémentaire nécessaire ici...
        echo ""
}
TRAP_ON # Active trap pour arrêter le script si une erreur est détectée.

# Retrieve arguments
app=$YNH_APP_INSTANCE_NAME

domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
is_public=$YNH_APP_ARG_IS_PUBLIC

# Source app helpers
source /usr/share/yunohost/helpers

# Vérifie que les variables ne sont pas vides.
CHECK_VAR "$app" "app name not set"

CHECK_PATH      # Vérifie et corrige la syntaxe du path.
CHECK_DOMAINPATH        # Vérifie la disponibilité du path et du domaine.

# Créer le repertoire de destination et stocke son emplacement.
CHECK_FINALPATH # Vérifie que le dossier de destination n'est pas déjà utilisé.
sudo mkdir "$final_path"
ynh_app_setting_set $app final_path $final_path

# Enregistre les infos dans la config YunoHost
ynh_app_setting_set $app domain $domain
ynh_app_setting_set $app path $path
ynh_app_setting_set $app is_public $is_public

# Create system user named $app if doesn't exist already
if ! ynh_system_user_exists "$app"      # Test l'existence de l'utilisateur
then
	sudo useradd -d /var/www/$app --system --user-group $app --shell /bin/bash || (echo "Unable to create $app system account" >&2 && false)
fi

# Modify the random username
user=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{24\}\).*/\1/p')
sed -i "s@USERTOCHANGE@$user@g" ../conf/user.json
sed -i "s@PATHTOCHANGE@$path/@g" ../conf/config.js

# HACK: Change the socket.io path in the sources
#
# Is this still required ??????
#
#sed -i "s@PATHTOCHANGE@$path@g" ../sources/client/js/lounge.js

# Get the sources
lounge_file=`sudo cat ../sources/source_file`;
sudo wget -nv -i ../sources/source_url -O ${lounge_file}.zip
sudo md5sum -c ../sources/source_md5 --status || (echo "Corrupt source" >&2 && false)
sudo unzip -q ${lounge_file}.zip -d ../sources/
sudo cp -r ../sources/${lounge_file}/. $final_path
# Copy files to the right place
sudo mkdir -p $final_path/.lounge/users
sudo cp ../conf/config.js $final_path/.lounge/
sudo cp ../conf/user.json $final_path/.lounge/users/$user.json

# Set permissions
sudo chown -hR $app: $final_path

# Install dependencies
sudo apt-get update
sudo apt-get install nodejs npm -y
sudo su - $app -c "cd $final_path && /usr/bin/npm install --production"

# Modify Nginx configuration file and copy it to Nginx conf directory
#if [[ "$path" == "" ]]; then
#  sed -i "s@LOCATIONTOCHANGE@/@g" ../conf/nginx.conf
#else
  sed -i "s@LOCATIONTOCHANGE@$path@g" ../conf/nginx.conf
#fi
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Copy systemd service
sed -i "s@NAMETOCHANGE@$$app@g" ../conf/systemd.service
sudo cp ../conf/systemd.service /etc/systemd/system/$app.service

# Add YunoHost service
sudo yunohost service add $app -l /var/log/syslog

# Make app public if necessary
is_public=$(ynh_app_setting_get $app is_public)
if [ "$is_public" = "Yes" ];
then
        ynh_app_setting_set $app skipped_uris "/"
else
        ynh_app_setting_set $app protected_uris "/"
fi

# Reload Nginx, thelounge and regenerate SSOwat conf
sudo service nginx reload
sudo systemctl enable $app
sudo systemctl start $app || sudo systemctl restart $app

sudo yunohost app ssowatconf
