#!/bin/bash

source .fonctions       # Charge les fonctions génériques habituellement utilisées dans le script

# Récupère les infos de l'application.
app=$YNH_APP_INSTANCE_NAME

# Source app helpers
source /usr/share/yunohost/helpers

domain=$(ynh_app_setting_get $app domain)
path=$(ynh_app_setting_get $app path)
final_path=$(ynh_app_setting_get $app final_path)
is_public=$(ynh_app_setting_get $app is_public)

CHECK_PATH      # Vérifie et corrige la syntaxe du path.

# Retrieve port and use it
port=$(ynh_app_setting_get $app port)
sed -i "s@PORTTOCHANGE@$port@g" ../conf/nginx.conf
sed -i "s@PORTTOCHANGE@$port@g" ../conf/config.js


# Create user named $app if doesn't exist already
if ! ynh_system_user_exists "$app"      # Test l'existence de l'utilisateur
then
        sudo useradd -d /var/www/$app --system --user-group $app --shell /bin/bash || (echo "Unable to create $app system account" >&2 && false)
fi

# Modify the random username
user=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{24\}\).*/\1/p')
sed -i "s@USERTOCHANGE@$user@g" ../conf/user.json
sed -i "s@PATHTOCHANGE@$path/@g" ../conf/config.js

# HACK: Change the socket.io path in the sources
#
# Is this still required ??????
#
#sed -i "s@PATHTOCHANGE@$path@g" ../sources/client/js/lounge.js

# Get the sources
lounge_file=`sudo cat ../sources/source_file`;
sudo wget -nv -i ../sources/source_url -O ${lounge_file}.zip
sudo md5sum -c ../sources/source_md5 --status || (echo "Corrupt source" >&2 && false)
sudo unzip -q ${lounge_file}.zip -d ../sources/
sudo cp -r ../sources/${lounge_file}/. $final_path
# Copy files to the right place
sudo mkdir -p $final_path/.lounge/users
sudo cp ../conf/config.js $final_path/.lounge/
sudo cp ../conf/user.json $final_path/.lounge/users/$user.json

# Set permissions
sudo chown -hR $app: $final_path

# Install dependencies
sudo apt-get update
sudo apt-get install nodejs npm -y
sudo su - $app -c "cd $final_path && /usr/bin/npm install --production"

# Modify Nginx configuration file and copy it to Nginx conf directory
#if [[ "$path" == "" ]]; then
#  sed -i "s@LOCATIONTOCHANGE@/@g" ../conf/nginx.conf
#else
  sed -i "s@LOCATIONTOCHANGE@$path@g" ../conf/nginx.conf
#fi
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Copy systemd service
sed -i "s@NAMETOCHANGE@$$app@g" ../conf/systemd.service
sudo cp ../conf/systemd.service /etc/systemd/system/$app.service

# Add YunoHost service
sudo yunohost service add $app -l /var/log/syslog \
  || echo "Service $app already exist"

# Make app public if necessary
is_public=$(ynh_app_setting_get $app is_public)
if [ "$is_public" = "Yes" ];
then
        ynh_app_setting_set $app skipped_uris "/"
else
        ynh_app_setting_set $app protected_uris "/"
fi

# Reload Nginx, thelounge and regenerate SSOwat conf
sudo service nginx reload
sudo systemctl enable $app
sudo systemctl restart $app || sudo systemctl start $app

sudo yunohost app ssowatconf
